language: python
# python versions to use during the tests
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install pylint
# command to run tests
script:
    - python setup.py install
    - python -m compileall -f park_vorhersage
    - pylint --errors-only park_vorhersage
